# Generated by Django 4.2.4 on 2023-09-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
